
(module
  (func $name (result i32) (i32.const 0))
  (func $version (result i32) (i32.const 1))
  (func $init (result i32) (i32.const 0))
  (func $health (result i32) (i32.const 0))
  (func $shutdown (result i32) (i32.const 0))
  (func $calculate (result i32) (i32.const 10))
  (export "name" (func $name))
  (export "version" (func $version))
  (export "init" (func $init))
  (export "health" (func $health))
  (export "shutdown" (func $shutdown))
  (export "calculate" (func $calculate))
)
